//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGRLSV
{
    using System;
    using System.Collections.Generic;
    
    public partial class diemDanhGiaRenLuyen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public diemDanhGiaRenLuyen()
        {
            this.ketQua = new HashSet<ketQua>();
        }
    
        public string namHoc { get; set; }
        public string maHK { get; set; }
        public string MSSV { get; set; }
        public Nullable<int> maCT { get; set; }
        public Nullable<int> diemSV { get; set; }
        public Nullable<int> diemLT { get; set; }
        public Nullable<int> diemCVHT { get; set; }
        public string maLC { get; set; }
    
        public virtual noiDungChiTiet noiDungChiTiet { get; set; }
        public virtual luaChonChiTiet luaChonChiTiet { get; set; }
        public virtual sinhVien sinhVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ketQua> ketQua { get; set; }
    }
}
