//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGRLSV
{
    using System;
    using System.Collections.Generic;
    
    public partial class ketQua
    {
        public int idKQ { get; set; }
        public string MSSV { get; set; }
        public string namHoc { get; set; }
        public string maHK { get; set; }
        public Nullable<int> tongDiemSV { get; set; }
        public Nullable<int> tongDiemLT { get; set; }
        public Nullable<int> tongDiemCVHT { get; set; }
        public string xepLoai { get; set; }
    
        public virtual diemDanhGiaRenLuyen diemDanhGiaRenLuyen { get; set; }
        public virtual sinhVien sinhVien { get; set; }
    }
}
