//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGRLSV
{
    using System;
    using System.Collections.Generic;
    
    public partial class luaChonChiTiet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public luaChonChiTiet()
        {
            this.diemDanhGiaRenLuyen = new HashSet<diemDanhGiaRenLuyen>();
        }
    
        public string maLC { get; set; }
        public string moTa { get; set; }
        public Nullable<int> diemMin { get; set; }
        public Nullable<int> diemMax { get; set; }
        public Nullable<int> maCT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<diemDanhGiaRenLuyen> diemDanhGiaRenLuyen { get; set; }
        public virtual noiDungChiTiet noiDungChiTiet { get; set; }
    }
}
