//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGRLSV
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DGRLEF : DbContext
    {
        public DGRLEF()
            : base("name=DGRLEF")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<diemDanhGiaRenLuyen> diemDanhGiaRenLuyen { get; set; }
        public virtual DbSet<giangVien> giangVien { get; set; }
        public virtual DbSet<ketQua> ketQua { get; set; }
        public virtual DbSet<khoa> khoa { get; set; }
        public virtual DbSet<lop> lop { get; set; }
        public virtual DbSet<luaChonChiTiet> luaChonChiTiet { get; set; }
        public virtual DbSet<noiDungChiTiet> noiDungChiTiet { get; set; }
        public virtual DbSet<sinhVien> sinhVien { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tieuChiDanhGia> tieuChiDanhGia { get; set; }
    }
}
