//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGRLSV
{
    using System;
    using System.Collections.Generic;
    
    public partial class noiDungChiTiet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public noiDungChiTiet()
        {
            this.diemDanhGiaRenLuyen = new HashSet<diemDanhGiaRenLuyen>();
            this.luaChonChiTiet = new HashSet<luaChonChiTiet>();
        }
    
        public int maCT { get; set; }
        public string ndChiTiet { get; set; }
        public Nullable<int> diemCTMax { get; set; }
        public Nullable<int> maTC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<diemDanhGiaRenLuyen> diemDanhGiaRenLuyen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<luaChonChiTiet> luaChonChiTiet { get; set; }
        public virtual tieuChiDanhGia tieuChiDanhGia { get; set; }
    }
}
